version: '3.8'

services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    hostname: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Europe/Sofia
      DEBIAN_FRONTEND: noninteractive
    restart: unless-stopped
    entrypoint: /entrypoint.sh
    ports:
      - "8081:80"
    networks:
      - mynet
    volumes:
      - ../src/:/mnt/csv-products
    command: --default-time-zone='Europe/Sofia'
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_csv
    hostname: mysql_csv
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: csvDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      TZ: Europe/Sofia
      DEBIAN_FRONTEND: noninteractive
    ports:
      - "33306:3306"
    networks:
      - mynet
    volumes:
      - mysql_store:/var/lib/mysql
    command: --default-time-zone='Europe/Sofia'
   
networks:
  mynet:
    driver: bridge
volumes:
  mysql_store:
    driver: local